name: Markdown lint

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run markdown lint
      uses: nosborn/github-action-markdown-cli@v3.4.0
      with:
        files: README.md
        config_file: .markdownlint.json
